/**
 * WOARU Multi-LLM AI Code Review Configuration
 * Generated by woaru setup llm
 */

module.exports = {
  "ai": {
    "providers": [
      {
        "id": "openai-gpt4",
        "providerType": "openai",
        "apiKeyEnvVar": "OPENAI_API_KEY",
        "baseUrl": "https://api.openai.com/v1/chat/completions",
        "model": "gpt-4o",
        "headers": {},
        "bodyTemplate": "{\"model\":\"{model}\",\"messages\":[{\"role\":\"system\",\"content\":\"{systemPrompt}\"},{\"role\":\"user\",\"content\":\"{prompt}\\\\n\\\\nCode to analyze:\\\\n```{language}\\\\n{code}\\\\n```\"}],\"max_tokens\":4000,\"temperature\":0.1}",
        "timeout": 30000,
        "maxTokens": 4000,
        "temperature": 0.1,
        "enabled": true
      }
    ],
    "parallelRequests": true,
    "consensusMode": false,
    "minConsensusCount": 2,
    "tokenLimit": 8000,
    "costThreshold": 0.5
  }
};
