http:
  middlewares:
    # HTTPS Redirect
    https-redirect:
      redirectScheme:
        scheme: https
        permanent: true

    # Security Headers
    default-headers:
      headers:
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https

    # Rate Limiting
    default-ratelimit:
      rateLimit:
        average: 100
        burst: 50

    # CORS for APIs
    cors-headers:
      headers:
        accessControlAllowMethods:
          - GET
          - OPTIONS
          - PUT
          - POST
          - DELETE
          - PATCH
        accessControlAllowHeaders:
          - "*"
        accessControlAllowOriginList:
          - "https://hrthis.kibubot.com"
        accessControlMaxAge: 100
        addVaryHeader: true