name: CI/CD Pipeline

on:
  push:
    branches: [ main ] # Oder dein Haupt-Branch-Name

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Change to Frontend Directory
        run: cd HRthis # HIER wechseln wir in den Frontend-Ordner

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Run npm audit
        run: npm audit --production
        continue-on-error: true

      - name: Build Frontend
        run: npm run build

      - name: Upload dependency check results
        uses: actions/upload-artifact@v4 # <-- HIER IST DIE KORRIGIERTE VERSION
        with:
          name: dependency-check-report
          path: reports/
          retention-days: 7
