name: HRthis CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  quality-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'HRthis/package-lock.json'

      - name: Install Frontend Dependencies
        run: npm install
        working-directory: ./HRthis

      - name: Run ESLint
        run: npm run lint -- --max-warnings 0
        working-directory: ./HRthis

  deploy-frontend:
    runs-on: ubuntu-latest
    needs: quality-check
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy Frontend to CapRover
        uses: caprover/deploy-action@v2
        with:
          server: "${{ secrets.CAPROVER_SERVER }}"
          app: "${{ secrets.CAPROVER_FRONTEND_APP_NAME }}"
          password: "${{ secrets.CAPROVER_PASSWORD }}"
          branch: "main"
          source: './HRthis'

  deploy-backend:
    runs-on: ubuntu-latest
    needs: quality-check
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy Backend to CapRover
        uses: caprover/deploy-action@v2
        with:
          server: "${{ secrets.CAPROVER_SERVER }}"
          app: "${{ secrets.CAPROVER_BACKEND_APP_NAME }}"
          password: "${{ secrets.CAPROVER_PASSWORD }}"
          branch: "main"
          source: './browo-hrthis-backend'
