name: Deploy HRthis Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to CapRover
        uses: caprover/deploy-action@v2
        with:
          server: "${{ secrets.CAPROVER_SERVER }}"
          app: "${{ secrets.CAPROVER_FRONTEND_APP_NAME }}"
          password: "${{ secrets.CAPROVER_PASSWORD }}"
          branch: "main"
          source: "./HRthis"
